// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface ActualOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.Actual)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required int64 actual = 1;</code>
   */
  boolean hasActual();
  /**
   * <code>required int64 actual = 1;</code>
   */
  long getActual();

  /**
   * <code>required int64 expect = 2;</code>
   */
  boolean hasExpect();
  /**
   * <code>required int64 expect = 2;</code>
   */
  long getExpect();

  /**
   * <code>required int32 actual_symbol = 3;</code>
   */
  boolean hasActualSymbol();
  /**
   * <code>required int32 actual_symbol = 3;</code>
   */
  int getActualSymbol();

  /**
   * <code>required int32 expect_symbol = 4;</code>
   */
  boolean hasExpectSymbol();
  /**
   * <code>required int32 expect_symbol = 4;</code>
   */
  int getExpectSymbol();
}